# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1db40d32d718588682de916722fe60ff1ad0ac59b1747672f21934702af70ea7fc42c44173c4fbad8e721618060fb3ff3290ca4d9a609373064e587edeb8df2e

test:
  secret_key_base: f18e84b5d0253cbbfc8cd0b3dd8ae43ddbd937e97c34bfa9d4a93dca5b0eb2d32d9634062bb94075cebe4cfdeb576be0c152772e64bb54d2e04855f4db160f3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
